import importlib


def test_domain_packages_are_importable():
    modules = [
        "app.common.security",
        "app.domains",
        "app.domains.developer",
        "app.domains.developer.indexing_service",
        "app.domains.developer.router",
        "app.domains.auth",
        "app.domains.auth.models",
        "app.domains.auth.repository",
        "app.domains.auth.router",
        "app.domains.auth.schemas",
        "app.domains.auth.service",
        "app.domains.classroom.schemas",
        "app.domains.classroom.teacher_router",
        "app.domains.classroom.student_view_router",
        "app.domains.classroom.dependencies",
        "app.domains.classroom.models",
        "app.domains.classroom.repository",
        "app.domains.classroom.service",
        "app.domains.agent.schemas",
        "app.domains.agent.service",
        "app.domains.instruction.student_router",
        "app.domains.instruction.teacher_router",
        "app.domains.instruction.generation",
        "app.domains.instruction.models",
        "app.domains.instruction.repository",
        "app.domains.instruction.schemas",
        "app.domains.instruction.service",
        "app.domains.content.router",
        "app.domains.content.stage1.router",
        "app.domains.content.stage1.schemas",
        "app.domains.content.stage1.service",
        "app.domains.content.stage2.router",
        "app.domains.content.stage2.schemas",
        "app.domains.content.stage2.service",
        "app.domains.progress.router",
        "app.domains.content.stage3.router",
        "app.domains.content",
        "app.domains.content.models",
        "app.domains.content.repository",
        "app.domains.content.schemas",
        "app.domains.content.service",
        "app.domains.progress.models",
        "app.domains.progress.repository",
        "app.domains.progress.schemas",
        "app.domains.progress.service",
        "app.domains.content.stage3.schemas",
        "app.domains.content.stage3.service",
        "app.domains.agent",
        "app.domains.agent.router",
        "app.domains.agent.schemas",
        "app.infrastructure.rag",
        "app.infrastructure.rag.retriever",
        "app.infrastructure.rag.schemas",
        "app.infrastructure.rag.service",
        "app.infrastructure.db.mongo.indexes",
    ]

    for module_name in modules:
        assert importlib.import_module(module_name)
