import importlib


def test_domain_packages_are_importable():
    modules = [
        "app.common.security",
        "app.domains",
        "app.domains.developer",
        "app.domains.developer.indexing_service",
        "app.domains.developer.router",
        "app.domains.auth",
        "app.domains.auth.models",
        "app.domains.auth.repository",
        "app.domains.auth.router",
        "app.domains.auth.schemas",
        "app.domains.auth.service",
        "app.domains.classroom.controller.teacher_class_router",
        "app.domains.classroom.controller.student_class_router",
        "app.domains.progress.controller.teacher_router",
        "app.domains.classroom.dependency.dependencies",
        "app.domains.classroom.models",
        "app.domains.classroom.repository.repository",
        "app.domains.classroom.service.service",
        "app.domains.classroom.schema.schemas",
        "app.domains.agent.schemas",
        "app.domains.agent.service",
        "app.domains.instruction.controller.student_router",
        "app.domains.instruction.controller.teacher_router",
        "app.domains.instruction.service.generation",
        "app.domains.instruction.validation.validation",
        "app.domains.instruction.models",
        "app.domains.instruction.repository.repository",
        "app.domains.instruction.schema.schemas",
        "app.domains.instruction.service.service",
        "app.domains.content.controller.router",
        "app.domains.content.stage1.router",
        "app.domains.content.stage1.schemas",
        "app.domains.content.stage1.service",
        "app.domains.content.stage2.router",
        "app.domains.content.stage2.schemas",
        "app.domains.content.stage2.service",
        "app.domains.progress.controller.router",
        "app.domains.content.stage3.router",
        "app.domains.content",
        "app.domains.content.models",
        "app.domains.content.repository.repository",
        "app.domains.content.schema.schemas",
        "app.domains.content.service.service",
        "app.domains.progress.models",
        "app.domains.progress.repository.repository",
        "app.domains.progress.schema.schemas",
        "app.domains.progress.service.service",
        "app.domains.content.stage3.schemas",
        "app.domains.content.stage3.service",
        "app.domains.agent",
        "app.domains.agent.router",
        "app.domains.agent.schemas",
        "app.infrastructure.rag",
        "app.infrastructure.rag.retriever",
        "app.infrastructure.rag.schemas",
        "app.infrastructure.rag.service",
        "app.infrastructure.db.mongo.indexes",
    ]

    for module_name in modules:
        assert importlib.import_module(module_name)
